server:
  port: 8705

spring:
  rabbitmq:
    first:
      virtualHost: demo
      username: guest
      password: guest
      port: 5672
      host: 127.0.0.1
    second:
      virtualHost: demo
      username: guest
      password: guest
      port: 5672
      host: 127.0.0.1
      publisher-returns: true